### ISSUE TITLE
Stuck at gpt3.5

### ISSUE THREAD

**Issue by yejr0229** [crockwell/Cap3D#31]
Hi, I run this command 'python caption_clip_gpt.py --parent_dir './example_material' --openai_api_key 'Your-key' --gpt_type 'gpt3.5'', and have no reaction for 1 hour, I shut down the program and here is the outputs:

(Cap3D) (base) ➜  captioning_pipeline python caption_clip_gpt.py --parent_dir './example_material' --openai_api_key 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' --gpt_type 'gpt3.5'
100%|████████████████████████████████████████| 338M/338M [00:02<00:00, 133MiB/s]
############begin to generate final captions############
^CTraceback (most recent call last):
  File "/data/yejr/Cap3D-main/captioning_pipeline/caption_clip_gpt.py", line 110, in <module>
    summary = summarize_captions_gpt35(cur_final_caption)
  File "/data/yejr/Cap3D-main/captioning_pipeline/caption_clip_gpt.py", line 57, in summarize_captions_gpt35
    response = openai.ChatCompletion.create(
  File "/root/anaconda3/envs/Cap3D/lib/python3.9/site-packages/openai/_utils/_proxy.py", line 21, in __getattr__
    if isinstance(proxied, LazyProxy):
  File "/root/anaconda3/envs/Cap3D/lib/python3.9/abc.py", line 117, in __instancecheck__
    def __instancecheck__(cls, instance):
KeyboardInterrupt

How to solve this problem?

**Comment by crockwell** [comment]
Hello,

Hmm that is frustrating. It looks like it's stuck calling the Openai API. Most likely then this is not an issue with our codebase but rather something having to do with your OpenAI API setup. If I had to guess it could be some firewall or login issue. I'd recommend checking their repos and issues for further information.

Hope this helps!

Best,
Chris

**Comment by crockwell** [comment]
Closing for inactivity - feel free to reopen if you have other questions!
